package com.demo.boot.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("order_detail", "detail_id", OrderDetail.class);
		arp.addMapping("order_master", "order_id", OrderMaster.class);
		arp.addMapping("product_category", "category_id", ProductCategory.class);
		arp.addMapping("product_info", "product_id", ProductInfo.class);
	}
}

