package com.demo.boot.model;

import com.demo.boot.model.base.BaseOrderDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderDetail extends BaseOrderDetail<OrderDetail> {
	
}
