package com.demo.boot.model;

import com.demo.boot.model.base.BaseOrderMaster;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderMaster extends BaseOrderMaster<OrderMaster> {
	public static final OrderMaster dao = new OrderMaster().dao();
}
