package com.demo.boot.model;

import com.demo.boot.model.base.BaseProductInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductInfo extends BaseProductInfo<ProductInfo> {
	
}
